#!/bin/sh

set -eu
# use readlink so that $0 points to the right place even when executing
# the script via a symlink
export PDM_PROJECT="$(dirname "$(readlink -f "$0")")"

if [ ${DEBUG:-0} -eq 1 ]; then
    pdm run \
      pudb \
      -m grm._internal.main \
      "$@"
else
    pdm run \
      python -m grm._internal.main \
      "$@"
fi
